### ISSUE TITLE
`test_functions` not defined in 10BBOB example

### ISSUE THREAD

**Issue by ndangtt** [automl/LTO-CMA#1]
Hello,

I think the line
https://github.com/automl/LTO-CMA/blob/51fe86f275dedd23722a51889eb712f633cee019/examples/10BBOB/hyperparams.py#L89

should be:

```
'test_functions': fcn_names
```

**Comment by gresash** [comment]
Thank you for pointing this out. Unfortunately until now we overlooked the issue. With the latest commit this should be fixed.
