### ISSUE TITLE
`cur_obj_val` initial value

### ISSUE THREAD

**Issue by ndangtt** [automl/LTO-CMA#2]
When I run:

```
python gps_test.py examples/10BBOB
```

I get the error message:
```
  File "/home/nttd/RL/LTO-CMA/source/gps/agent/lto/cmaes_world.py", line 44, in run
    self.f_difference = np.abs(np.amax(self.func_values) - self.cur_obj_val)/float(self.cur_obj_val)
	AttributeError: 'CMAESWorld' object has no attribute 'cur_obj_val'
```

It was because `self.cur_obj_val` was not assigned in `CMAESWorld.__init__`. Which value should I use for the assignment?

**Comment by gresash** [comment]
Thank you for pointing this out. Unfortunately until now we overlooked the issue. With the latest commit this should be fixed.
